version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/ekyu.moe/vanity-monero
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run:
          name: gofmt
          command: diff -u <(echo -n) <(gofmt -d .)
      - run:
          name: govet
          command: go vet ./...
  release:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/ekyu.moe/vanity-monero
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  release:
    jobs:
      - lint
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
